springdoc:
  swagger-ui:
    enabled: true

server:
  port: 3000
spring:
  application:
    name: hostfully-service
  jpa:
    open-in-view: false
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: UNSPECIFIED
      hibernate:
        show_sql: true
        format_sql: true
