springdoc:
  swagger-ui:
    enabled: true

server:
  port: 3000
spring:
  application:
    name: hostfully-service
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:hostfully
    driverClassName: org.h2.Driver
    username: hostfully
    password: hostfully
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    open-in-view: false
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: UNSPECIFIED
      hibernate:
        show_sql: true
        format_sql: true
